//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryFinalBDDII.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_106
    {
        public int ID_106 { get; set; }
        public string CED106 { get; set; }
        public string B101 { get; set; }
        public string B102 { get; set; }
        public string B201 { get; set; }
        public string B202 { get; set; }
        public string B203 { get; set; }
        public string B204 { get; set; }
        public string B205 { get; set; }
        public string B301 { get; set; }
        public string B302 { get; set; }
        public string B303 { get; set; }
        public string B304 { get; set; }
        public string B305 { get; set; }
        public string B306 { get; set; }
        public string B198 { get; set; }
        public string B199 { get; set; }
        public Nullable<decimal> B902 { get; set; }
        public Nullable<decimal> B903 { get; set; }
        public Nullable<decimal> B904 { get; set; }
        public Nullable<decimal> B999 { get; set; }
        public Nullable<decimal> B905 { get; set; }
        public Nullable<decimal> B906 { get; set; }
        public Nullable<decimal> B907 { get; set; }
        public Nullable<decimal> B925 { get; set; }
        public string B908 { get; set; }
        public Nullable<decimal> B909 { get; set; }
        public string B910 { get; set; }
        public Nullable<decimal> B911 { get; set; }
        public string B912 { get; set; }
        public Nullable<decimal> B913 { get; set; }
        public string B914 { get; set; }
        public Nullable<decimal> B915 { get; set; }
        public string B916 { get; set; }
        public Nullable<decimal> B917 { get; set; }
        public string B918 { get; set; }
        public Nullable<decimal> B919 { get; set; }
        public Nullable<decimal> B920 { get; set; }
    }
}
