//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryFinalBDDII.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_102A
    {
        public int ID_102A { get; set; }
        public string CED102A { get; set; }
        public string A102 { get; set; }
        public string A104 { get; set; }
        public Nullable<int> A105 { get; set; }
        public string A201 { get; set; }
        public string A202 { get; set; }
        public Nullable<decimal> A481 { get; set; }
        public Nullable<decimal> A491 { get; set; }
        public Nullable<decimal> A710 { get; set; }
        public Nullable<decimal> A711 { get; set; }
        public Nullable<decimal> A721 { get; set; }
        public Nullable<decimal> A712 { get; set; }
        public Nullable<decimal> A722 { get; set; }
        public Nullable<decimal> A703 { get; set; }
        public Nullable<decimal> A713 { get; set; }
        public Nullable<decimal> A723 { get; set; }
        public Nullable<decimal> A704 { get; set; }
        public Nullable<decimal> A714 { get; set; }
        public Nullable<decimal> A724 { get; set; }
        public Nullable<decimal> A705 { get; set; }
        public Nullable<decimal> A715 { get; set; }
        public Nullable<decimal> A725 { get; set; }
        public Nullable<decimal> A716 { get; set; }
        public Nullable<decimal> A717 { get; set; }
        public Nullable<decimal> A718 { get; set; }
        public Nullable<decimal> A719 { get; set; }
        public Nullable<decimal> A720 { get; set; }
        public Nullable<decimal> A730 { get; set; }
        public Nullable<decimal> A731 { get; set; }
        public Nullable<decimal> A729 { get; set; }
        public Nullable<decimal> A741 { get; set; }
        public Nullable<decimal> A739 { get; set; }
        public Nullable<decimal> A751 { get; set; }
        public Nullable<decimal> A749 { get; set; }
        public Nullable<decimal> A759 { get; set; }
        public Nullable<decimal> A769 { get; set; }
        public Nullable<decimal> A768 { get; set; }
        public Nullable<decimal> A771 { get; set; }
        public Nullable<decimal> A772 { get; set; }
        public Nullable<decimal> A773 { get; set; }
        public Nullable<decimal> A774 { get; set; }
        public Nullable<decimal> A775 { get; set; }
        public Nullable<decimal> A776 { get; set; }
        public Nullable<decimal> A780 { get; set; }
        public Nullable<decimal> A777 { get; set; }
        public Nullable<decimal> A778 { get; set; }
        public Nullable<decimal> A779 { get; set; }
        public string A740 { get; set; }
        public string A750 { get; set; }
        public Nullable<decimal> A760 { get; set; }
        public Nullable<decimal> A770 { get; set; }
        public Nullable<decimal> A781 { get; set; }
        public Nullable<decimal> A782 { get; set; }
        public Nullable<decimal> A783 { get; set; }
        public Nullable<decimal> A784 { get; set; }
        public Nullable<decimal> A786 { get; set; }
        public Nullable<decimal> A787 { get; set; }
        public Nullable<decimal> A789 { get; set; }
        public Nullable<decimal> A832 { get; set; }
        public Nullable<decimal> A839 { get; set; }
        public Nullable<decimal> A840 { get; set; }
        public Nullable<decimal> A842 { get; set; }
        public Nullable<decimal> A843 { get; set; }
        public Nullable<decimal> A845 { get; set; }
        public Nullable<decimal> A846 { get; set; }
        public Nullable<decimal> A847 { get; set; }
        public Nullable<decimal> A848 { get; set; }
        public Nullable<decimal> A849 { get; set; }
        public Nullable<decimal> A850 { get; set; }
        public Nullable<decimal> A851 { get; set; }
        public Nullable<decimal> A852 { get; set; }
        public Nullable<decimal> A855 { get; set; }
        public Nullable<decimal> A856 { get; set; }
        public Nullable<decimal> A857 { get; set; }
        public Nullable<decimal> A858 { get; set; }
        public Nullable<decimal> A859 { get; set; }
        public Nullable<decimal> A869 { get; set; }
        public Nullable<decimal> A880 { get; set; }
        public Nullable<decimal> A881 { get; set; }
        public Nullable<decimal> A882 { get; set; }
        public Nullable<decimal> A879 { get; set; }
        public Nullable<decimal> A871 { get; set; }
        public Nullable<decimal> A872 { get; set; }
        public Nullable<decimal> A890 { get; set; }
        public Nullable<decimal> A897 { get; set; }
        public Nullable<decimal> A898 { get; set; }
        public Nullable<decimal> A899 { get; set; }
        public Nullable<decimal> A902 { get; set; }
        public Nullable<decimal> A903 { get; set; }
        public Nullable<decimal> A904 { get; set; }
        public Nullable<decimal> A999 { get; set; }
        public Nullable<decimal> A905 { get; set; }
        public Nullable<decimal> A906 { get; set; }
        public Nullable<decimal> A907 { get; set; }
        public string A908 { get; set; }
        public Nullable<decimal> A909 { get; set; }
        public string A910 { get; set; }
        public Nullable<decimal> A911 { get; set; }
        public string A912 { get; set; }
        public Nullable<decimal> A913 { get; set; }
        public Nullable<decimal> A915 { get; set; }
        public string A916 { get; set; }
        public Nullable<decimal> A917 { get; set; }
        public string A918 { get; set; }
        public Nullable<decimal> A919 { get; set; }
        public string A920 { get; set; }
        public string A198 { get; set; }
        public string NOMB102A { get; set; }
    }
}
